// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Info struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type LoginInfo struct {
	Success bool        `json:"success"`
	Info    *ReturnUser `json:"info,omitempty"`
}

type LoginUserForm struct {
	UserName *string `json:"userName,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password string  `json:"password"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type Query struct {
}

type ReturnUser struct {
	UserName string `json:"userName"`
	UserID   string `json:"userID"`
	Email    string `json:"email"`
}

type Todo struct {
	ID      string `json:"id"`
	Text    string `json:"text"`
	Done    bool   `json:"done"`
	OwnerID string `json:"ownerID"`
}

type User struct {
	UserID   string `json:"userID"`
	UserName string `json:"userName"`
	Password string `json:"password"`
	Email    string `json:"email"`
}
