// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Info struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type Query struct {
}

type Todo struct {
	ID      string `json:"id"`
	Text    string `json:"text"`
	Done    bool   `json:"done"`
	OwnerID string `json:"ownerID"`
}

type User struct {
	UserID       string `json:"userID"`
	UserName     string `json:"userName"`
	Password     string `json:"password"`
	Email        string `json:"email"`
	RegisteredAt string `json:"registeredAt"`
}
