# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Todo {
  id: String!
  text: String!
  done: Boolean!
  ownerID: String!
}

# User defines a single user
type User {
  userID: String!
  userName: String!
  password: String!
  email: String!
}

# Info defines the info for returning
type Info {
  success: Boolean!
  message: String!
}

# ReturnUser defines the schema for returning info to user
type ReturnUser{
  userName: String!
  userID: String!
  email: String!
}

# LoginInfo defines the schema for returing user info when logged in
type LoginInfo{
  success: Boolean!
  info: ReturnUser
}

# NewTodo defines schema for creating todo
input NewTodo {
  text: String!
  userId: String!
}

# NewUser defines the schema for creating user
input NewUser {
  userName: String!
  password: String!
  email: String!
}

# LoginUserForm defines form for login
input LoginUserForm{
  userName: String
  email: String
  password: String!
}

# Mutation: Change data
type Mutation {
  # createTodo creates new todo
  createTodo(input: NewTodo!): Info!
  # createUser creates new user
  createUser(input: NewUser!): Info!
  # verifyUser verifies user
  verifyUser: Info!
}

# Query: Get data
type Query {
  # todos gets all the todos
  todos: [Todo!]!
  # login logins the system
  login(input: LoginUserForm): LoginInfo!
}
