# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Todo {
  id: String!
  text: String!
  done: Boolean!
  ownerID: String!
}

type User {
  userID: String!
  userName: String!
  password: String!
  email: String!
  registeredAt: String!
}

# Info defines the info for returning
type Info {
  success: Boolean!
  message: String!
}

type Query {
  todos: [Todo!]!
}

input NewTodo {
  text: String!
  userId: String!
}

# NewUser defines the schema for creating user
input NewUser {
  userName: String!
  password: String!
  email: String!
}

type Mutation {
  createTodo(input: NewTodo!): Info!
  createUser(input: NewUser!): Info!
}
