package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/1Vewton/MaterialScienceTV/backend/graph/model"
	"github.com/1Vewton/MaterialScienceTV/backend/internal/cookie"
	"github.com/1Vewton/MaterialScienceTV/backend/internal/database"
	"github.com/1Vewton/MaterialScienceTV/backend/internal/database/redismanager"
	"github.com/1Vewton/MaterialScienceTV/backend/internal/user"
	"github.com/1Vewton/MaterialScienceTV/backend/pkg/config"
	"github.com/google/uuid"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Info, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.Info, error) {
	// Get writer
	writer, err := cookie.GetResponseWriterFromContext(
		ctx,
	)
	if err != nil {
		return &model.Info{
			Success: false,
		}, err
	}
	request, err := cookie.GetRequestFromContext(
		ctx,
	)
	if err != nil {
		return &model.Info{
			Success: false,
		}, err
	}
	_, err = request.Cookie(cookie.RegisterTokenKey)
	if err != http.ErrNoCookie {
		if err == nil {
			return &model.Info{
					Success: false,
				}, errors.New(
					"you already submitted a register request",
				)
		}
		return &model.Info{
			Success: false,
		}, err
	}
	// New tmp user
	token := redismanager.NewToken("register")
	newUserID := uuid.NewString()
	newTmpUser := user.NewTmpUser(
		newUserID,
		input.UserName,
		input.Password,
		input.Email,
	)
	userLifetime, err := config.Config.GetTmpUserLifetime()
	if err != nil {
		return &model.Info{
			Success: false,
		}, err
	}
	err = newTmpUser.UploadToRedis(
		ctx,
		redismanager.RedisClient,
		token,
		time.Duration(userLifetime)*time.Minute,
	)
	if err != nil {
		return &model.Info{
			Success: false,
		}, err
	}
	// Set cookie
	cookie := http.Cookie{
		Name:   cookie.RegisterTokenKey,
		Value:  token,
		MaxAge: userLifetime * 60,
	}
	writer.Header().Set(
		"Set-Cookie",
		cookie.String(),
	)
	return &model.Info{
		Success: true,
	}, nil
}

// VerifyUser is the resolver for the verifyUser field.
func (r *mutationResolver) VerifyUser(ctx context.Context) (*model.Info, error) {
	// Get token stored in cookies
	request, err := cookie.GetRequestFromContext(
		ctx,
	)
	if err != nil {
		return &model.Info{
			Success: false,
		}, err
	}
	requestCookie, err := request.Cookie(cookie.RegisterTokenKey)
	if err != nil {
		if err == http.ErrNoCookie {
			return &model.Info{
					Success: false,
				}, errors.New(
					"session expired or not exists",
				)
		}
		return &model.Info{
			Success: false,
		}, err
	}
	token := requestCookie.Value
	tmpUser, err := user.GetTmpUser(
		ctx,
		redismanager.RedisClient,
		token,
	)
	if err != nil {
		return &model.Info{
			Success: false,
		}, err
	}
	realUser := tmpUser.ToUserData()
	err = user.AddUser(
		ctx,
		database.DataBase,
		realUser,
	)
	if err != nil {
		return &model.Info{
			Success: false,
		}, err
	}
	return &model.Info{
		Success: true,
	}, err
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
